### ISSUE TITLE
Feature: Cache repo?

### ISSUE THREAD

**Issue by TheEmpty** [ericpaulbishop/redmine_git_hosting#7]
I'm not really sure how this works, but it's quite annoying that everytime someone clicks on the repo button that it connects to the git server. It takes time and resources, as well as opening up a GREAT way to DDoS. So perhaps a cache setup to only check it once every x minutes or never at all (via the panel). The never at all option would assume that the user has a hook or daemon to update it (I wouldn't mind having a hook update it).

Let me know if these features are spamming you too much and I'll just fork you and put the issues there.

**Comment by ericpaulbishop** [comment]
I don't mind the issues being posted... it's not spamming.  I just
can't give you a guarantee on when I'm going to get around to
addressing some of these.  As I said before, contributions are very
welcome.

Eric

On Thu, May 12, 2011 at 1:47 PM, TheEmpty
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
Correct me if I'm wrong, but doesn't that only happen if your Autofetch commits Redmine option is checked? If your repo is updated on every push, then that option doesn't even need to be on, since the repository is refreshed on each push, MUCH better imho.

I do this with my repositories, and it definitely makes viewing the repository fast.

The above of course doesn't apply, if that option has no effect on the plugin connecting to the server, which would be pretty bad (I think that'd be a bug and loophole). I doubt that it does that though.

**Comment by ericpaulbishop** [comment]
Yeah, I thing the TheEmpty is referring to the normal check which is part of the built-in functionality.  I'm pretty sure it isn't connecting to gitolite on every page load.  Since the option to turn off fetching already exists I'm just going to close this issue.

**Comment by TheEmpty** [comment]
Every time I hit repository it logs into the Git SSH. I've watched the

On Fri, May 13, 2011 at 5:01 PM, ericpaulbishop <
reply@reply.github.com>wrote:

> Yeah, I thing the TheEmpty is referring to the normal check which is part
> of the built-in functionality.  I'm pretty sure it isn't connecting to
> gitolite on every page load.  Since the option to turn off fetching already
> exists I'm just going to close this issue.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ericpaulbishop/redmine_git_hosting/issues/7#comment_1157323

## 

This E-Mail address is facetime enabled
Sent from my Windows 7 PC
