### ISSUE TITLE
Troubles with FreeBSD configuration

### ISSUE THREAD

**Issue by dermyrddin** [ericpaulbishop/redmine_git_hosting#79]
The system is:
FreeBSD 8.1
nginx/1.0.6
passenger 3.0.9
sudo 1.8.2
Redmine 1.2.1
redmine_git_hosting 0.4.0
key name is git_id_rsa(.pub)

I have all possible troubles, I think =)

First of all at Repositories tab in Configuration I see "/tmp/redmine_git_hosting/run_git_as_git_user" as a Git command. As I understand viewing last comments - this should be fixed in the last version of plugin?

Then in the plugin settings both sudo checks have exclamation marks, but if I run manualy "sudo -nu www echo yes" or "sudo -nu git echo yes" all seems to be ok.

Also if I try to add a public key in user settings I recieve "No such file or directory - /tmp/redmine_git_hosting/gitolite-admin/conf/gitolite.conf".

I've try solving this problems last few days withot success. Reinstalling, different rights combinations on /tmp/redmine_git_hosting, redmine/.ssh, /home/git folders doesn't help. I really confused what to do... Can anybody give the right direction to find the solution?

Thanks for any help!

**Comment by ericpaulbishop** [comment]
It's really hard to offer advice to this situation, because so much seems to be going wrong -- it's a lot easier if I can focus on one thing at a time.  Also, I can't reproduce the problem -- this is working fine for me.

/tmp/redmine_git_hosting/run_git_as_git_user is actually what you want as your git command.  Is it there?  has it been created properly?

What happens if you run su to become the www user and run /tmp/redmine_git_hosting/run_git_as_git_user --version ?  Does it print the git version?

**Comment by Tronix117** [comment]
Hello,

I'm dealing with the same issue, or quite.
On freeBSD, the following command return "yes"
`sudo -nu www sudo -nu git sudo -nu www echo "yes"`

But from chiliproject log I get that:

```
Testing if git user("git") can sudo to web user("www")
Error while testing sudo_git_to_web_user: 
Testing if web user("www") can sudo to git user("git")
Error while testing sudo_web_to_git_user: 
"post-receive" not handled by gitolite, installing it...
Installing "post-receive.redmine_gitolite.rb" from /usr/local/www/chiliproject/vendor/plugins/redmine_git_hosting/contrib/hooks/post-receive.redmine_gitolite.rb to ~/.gitolite/hooks/common/post-receive
```

"post-receive.redmine_gitolite installed
Running "gl-setup" on the gitolite install...
Finished installing hooks in the gitolite install...

Edit: `sudo -nu www /tmp/redmine_git_hosting/run_git_as_git_user --version` works also fine and return: `git version 1.7.3.5`
On an other hand, I forgot to tell you that my `www` user has no shell or no home, but I guess it doesn't really matter

**Comment by ericpaulbishop** [comment]
It matters very much that www has no shell.  Set one and then try it.

**Comment by Tronix117** [comment]
Thank you for your answer, I just tried and no changes. The two test methods still don't work.

By the way, why is the shell really matter ? isn't "sudo" enough ?

(I'm using apache/passenger btw)

**Comment by ericpaulbishop** [comment]
Hmm... that is odd. Are you absolutely certain that "www" is definitely the user apache/passenger is running as?  Also, you may want to restart your webserver as the tests do get cached, and are cleared when the web server restarts.

What happens if you edit redmine_git_hosting/lib/git_hosting.rb, and insert at line 86 (first line of self.sudo_web_to_git_user) the followng:

pass_user=%x[echo $USER ]
logger.warn "PASSENGER USER = #{pass_user}"

What do you see in your logs?

Well, I'm not 100% certain if a lack of shell would be a problem (I haven't tried it) but it's a huge potential problem.  I think the shell determines PATH environment variables, and if these don't get set, you're in trouble since the user may not know where certain commands are.  I think the exact process of loading environment variables depends on the system a bit, but I could easily see something like this causing a problem.  But then again, I'm not sure, I'd have to just try it.

**Comment by Tronix117** [comment]
About my passenger user I'm really sure ;), I even change permission to allow maximum access for the www user. 
There is something really weird, when I print the result of the test `sudo -nu #{git_user} echo "yes"`, there is nothing in output, whereas if I run something like `echo "#{git_user}"`, it works great and output `git`.

But I really don't understand because if I execute all those commands in a shell with `www` user, all is working. I guess there is some protection somewhere which prevent passenger to call "sudo"

```
Testing if web user("www") can sudo to git user("git")
Error while testing sudo_web_to_git_user:   
PASSENGER USER = www 
Testing if web user("www") can sudo to git user("git")
Test result =
Test echo git_user = git
PASSENGER USER = www
```

**Comment by ericpaulbishop** [comment]
I wonder if we could simplify the testing of this issue.  Suppose you just create a really simple ruby script, test.rb:

```
sudo_test= %x[ sudo -nu git echo "yes"]
puts "sudo test = " + sudo_test
```

Then just run ruby test.rb as the web user and see what happens.  Does it work?  If not.. we can see what can be done to get this really simple test to work without bothering with the rest of the plugin.

**Comment by ericpaulbishop** [comment]
Also, can you test which version of sudo you're using?  (run sudo -V)

**Comment by Tronix117** [comment]
it works
so the problem seems to be related to passenger

```
(#) su www
$ ruby test.rb
$ sudo test = yes
```

**Comment by ericpaulbishop** [comment]
Ok, slowly narrowing it down....

Let's go back to editing redmine_git_hosting/lib/git_hosting.rb where you did last time.  Next thing to test is whether passenger can run sudo at all.  Suppose we add the following lines to the script:
    sudo_test=%x[sudo -V ]
    logger.warn "SUDO VERSION INFO = #{sudo_test}"

Do we get any output from the sudo test when we're just trying to print sudo version information?

Is there any difference if you replace %x[sudo -V] with %x[/usr/bin/sudo -V] -- that is, specifying the full path to sudo (I'm assuming it's /usr/bin/sudo, it might be different on your system).  Basically, I'm checking whether sudo is in the PATH for Passenger.  If it isn't, it won't ever get run.

**Comment by Tronix117** [comment]
Well done ! You were right, it was the PATH which wasn't preserve through the `sudo`
I managed it quickly with a `ln -s /usr/local/bin/sudo /usr/bin/` and it seems working (tests ok)

I will take a deeper look tomorrow (already 5am in my part of the world).

Thank you for your time !

Edit: Now I've got the same problem as Merlineus, when I try to add some public key, but I'll try to figure it out
Edit 2: Solve the Merlineus problem (error 500) with the same dirty method: `ln -s /usr/local/bin/git /usr/bin/`, but it seems that it still can't update the gitalite-admin (but nothing in logs)

**Comment by Tronix117** [comment]
To solve the PATH problem when using Apache/Passenger (more global issue, not specific to this plugin):
I assume the following (but can be adapted to any other configurations):
- `/usr/local/etc/apache22/httpd.conf` is the file where you have configured Passenger variables
- `/usr/local/bin/ruby18` is the ruby executable
- PATH must be: `/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin`

Steps:
1. Create a new file: /usr/local/bin/ruby18env
    #!/bin/sh
    export PATH="/usr/local/lib/ruby/gems/1.8/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
    /usr/local/bin/ruby18 $*
2. Make this file executable: `chmod 755 /usr/local/bin/ruby18env`
3. Edit your /usr/local/etc/apache22/httpd.conf
- Replace or add `PassengerRuby /usr/local/bin/ruby18` 
- By `PassengerRuby /usr/local/bin/ruby18env`

Then all issue relative to a bad PATH will be solved.

All is working perfectly well now, thank you for your help ericpaulbishop

**Comment by dermyrddin** [comment]
Hello, sorry for the long absence.
1. Yes, my "scm_git_command" is set to "/tmp/redmine_git_hosting/run_git_as_git_user" and it is in the right place with this permissions:

drwx------   2 www     wheel     512 Sep 19 00:45 redmine_git_hosting

-r-xr-x---   1 www   wheel  122 Sep 19 00:29 gitolite_admin_ssh
-r-xr-x---   1 www   wheel  236 Sep 19 00:29 run_as_git_user
-r-xr-x---   1 www   wheel  167 Sep 19 00:29 run_git_as_git_user
1. "sudo -nu www /tmp/redmine_git_hosting/run_git_as_git_user --version" prints "git version 1.7.6"
2. I've implemented the fix from Tronix117 (Thanks!) so it solves the problem with permissions check and git command check is now green in Configuration.
3. So the one problem for now is "No such file or directory - /tmp/redmine_git_hosting/gitolite-admin/conf/gitolite.conf)" when I try to add or remove public key in the user settings.

**Comment by ericpaulbishop** [comment]
Is there anything in /tmp/redmine_git_hosting/gitolite-admin/ at all?  Or is it empty / non-existent ?

**Comment by dermyrddin** [comment]
I have no "/tmp/redmine_git_hosting/gitolite-admin/" at all.
Maybe I'll try to reinstall gitolite and redmine_git_hostnig.

**Comment by dermyrddin** [comment]
Finaly it works!
I think the problem was in wrong rights on git user home.
Thanks for your help.
