### ISSUE TITLE
Deleted Git repositories come back from the dead

### ISSUE THREAD

**Issue by Jehreg** [ericpaulbishop/redmine_git_hosting#82]
I wish it was Halloween...

To re-create, create a project, and create the git repo with it.

Check that the repo shows up in ~git/repositories/

Set the plugin config to auto-delete OFF.

Delete the project.

Notice that the Git repo is still in ~git/repositories/  which is totally normal.

Delete the repo from ~git/repositories/

RELOAD APACHE

Create another project, and create the git repo for that one.

Check in ~git/repositories/ and you will see the project that you just created, AND the project you deleted (I imagine it will just be a bare repo, not nodes in it).

Expected behaviour ?

This doesn't happen if I set the auto-delete on. 

My guess is that we are leaving info behind in the git_repository_extras table when we delete a project without repo auto-delete.

**Comment by ericpaulbishop** [comment]
I don't think this is a bug, but rather associated with what you need to do to delete a repo in gitolite.  Gitolite automatically creates repos it has definitions for when you push the admin repo, if the repo doesn't already exist.  The admin repo gets pushed when a new project is created, the definition isn't gone, and voila -- your repo is resurrected.

The whole point of not deleting the repo in gitolite even when it is deleted in Redmine is that we may have repos we want to manage only with gitolite, without Redmine.  So, in this case you have to delete the repo like you would any other repo in gitolite -- you have to both delete the directory AND remove it from the gitolite config file.  If you DO want to manage all your repos with Redmine, just switch on autodelete and the problem is solved.

**Comment by Jehreg** [comment]
Yup, you are right.
</gitolite noob>
