### ISSUE TITLE
problem cloning repository

### ISSUE THREAD

**Issue by gigaroby** [ericpaulbishop/redmine_git_hosting#88]
Hello, I installed the plugin on both redmine (trunk) and chiliproject 2.2.0 but I can't get it to work on either of them.
The problem is that when I try to create a project with a git repo I get this error :
Cloning gitolite-admin repository
Setting up /tmp/redmine_git_hosting
Installed hook digest: b007f793382102ff9f0f2a54b5a057c8
Creating MD5 digests for Redmine Git Hosting hook
Digest for post-receive.redmine_gitolite.rb: b007f793382102ff9f0f2a54b5a057c8
Our hook is already installed

Errno::ENOENT (No such file or directory - /tmp/redmine_git_hosting/gitolite-admin/conf/gitolite.conf):
  vendor/plugins/redmine_git_hosting/app/models/git_hosting_observer.rb:19:in `set_update_active'
  public/dispatch.fcgi:24

Rendering /srv/http/apps/redmine/public/500.html (500 Internal Server Error)

I have been trying everything but it doesnt work.

I have redmine running as user "redmine" with spawn-fcgi on a lighttpd web server and gitolite is installed as user "git".
I tried to execute "sudo -u git git clone /home/git/repositories/gitolite-admin.git" and it works.

**Comment by ericpaulbishop** [comment]
Do you have write permission for the /tmp directory?  Also, make sure your keys are installed properly and that you can clone the gitolite repo using them.

**Comment by gigaroby** [comment]
I have permissions to write on /tmp and I copied the ssh keys from the account I used to install gitolite so that is correct.
(sorry about closing and re-opening I pressed the wrong button)

**Comment by ericpaulbishop** [comment]
What exactly is in /tmp/redmine_git_hosting directory?  Does /tmp/redmine_git_hosting/gitolite-admin exist at all?

**Comment by gigaroby** [comment]
This is the result of the ls command into /tmp/redmine_git_hosting : 
gitolite_admin_ssh  run_as_git_user  run_git_as_git_user ... The forlder /tmp/redmine_git_hosting/gitolite-admin does not exist.
P.s: sorry again, I must be really dumb xD

**Comment by ericpaulbishop** [comment]
Sorry for taking so long to get back to you -- I've just been really busy for the past week.

One thing to check is the permissions on /tmp/redmine_git_hosting, if it's not owned by the webserver user (possibly do to running the migration as a different user, though I thought I had handled this case in the latest version) then you might get this result.

Also, what happens if you delete the /tmp/redmine_git_hosting directory, then restart the web server?  Does it start working, or do you get the same problem?

**Comment by gigaroby** [comment]
Fist of all thanks for answering at all,
I restarted it about a million times after deleting it, and the owner is indeed the redmine user (because I run it with spawn-fcgi).

**Comment by ericpaulbishop** [comment]
ok, what are the permissions on the ssh keys that redmine is using to do the clone, e.g. [redmine_root]/.ssh directory and the files in it?  Are you sure they are setup with the redmine user as owner and with 644 permissions on the public key and 600 permissions on the private key?

**Comment by majaesch** [comment]
I've got the same problem and sit her since friday. :-/

sudo ls -lah /tmp/redmine_git_hosting/
drwx------ 2 redmine redmine 4,0K 2011-09-26 20:05 .

sudo ls -lah ~redmine/apps/redmine/.ssh/
drwx------  2 redmine redmine 4,0K 2011-09-26 19:40 .
-rw-------  1 redmine root     744 2011-09-26 19:31 git_dsa
-rw-r--r--  1 redmine root     597 2011-09-26 19:31 git_dsa.pub
//
the .ssh files of the git user!
//
sudo cat ~/apps/redmine/vendor/plugins/redmine_git_hosting/init.rb
                'gitoliteIdentityFile' => RAILS_ROOT + '/.ssh/git_dsa',
                'gitoliteIdentityPublicKeyFile' => RAILS_ROOT + '/.ssh/git_dsa.pub',

btw:
sudo su redmine
git clone git@server:gitolite-admin
-> works!

**Comment by ericpaulbishop** [comment]
What if you do:

```
sudo su redmine
env GIT_SSH="/tmp/redmine_git_hosting/gitolite_admin_ssh" git clone git@server:gitolite-admin.git
```

What happens?  If you get error messages, what are they?

**Comment by majaesch** [comment]
Initialized empty Git repository in /opt/redmine/gitolite-admin/.git/
Permission denied (publickey,password).
fatal: The remote end hung up unexpectedly

strange!
$ sudo cat /etc/sudoers
redmine         ALL=(git)       NOPASSWD:ALL
git             ALL=(redmine)  NOPASSWD:ALL

**Comment by ericpaulbishop** [comment]
It's not a problem with sudo, it's an SSH problem.  SSH isn't liking the private key you're trying to use.  Can you show my the contents of your /tmp/redmine_git_hosting/gitolite_admin_ssh file? (this is just a script, it doesn't contain keys, and should be getting generated automatically)

```
cat /tmp/redmine_git_hosting/gitolite_admin_ssh
```

**Comment by majaesch** [comment]
It's okay, just a test on a vm.

#!/bin/sh
exec ssh -o BatchMode=yes -o StrictHostKeyChecking=no -i /opt/redmine/apps/redmine/.ssh/git_dsa "$@"

**Comment by ericpaulbishop** [comment]
In that case I'm highly suspicious of whether the key you have set has been given proper access in gitolite.  Suppose you create a new user and copy /opt/redmine/apps/redmine/.ssh/git_dsa to that user's .ssh directory, and rename it to "id_rsa".

Then, try cloning the gitolite admin repo as that user.

**Comment by majaesch** [comment]
Hope that's is what you wanted:

$ cp /opt/redmine/apps/redmine/.ssh/git_dsa to /home/majaesch/.ssh/id_rsa
$ ls -lah ~majaesch/.ssh/id_rsa
-rw------- 1 majaesch majaesch 744 2011-09-26 21:36 /home/majaesch/.ssh/id_rsa

$ git clone git@server:gitolite-admin
Initialized empty Git repository in /home/majaesch/gitolite-admin/.git/
Enter passphrase for key '/home/majaesch/.ssh/id_rsa':

git passphrase will not accepted

**Comment by ericpaulbishop** [comment]
This pretty much confirms that this is not an issue with this plugin, but with your gitolite key configuration.  Your ssh key (1) shouldn't require a passphrase and (2) doesn't seem to work even when you enter a passphrase, indicating that gitolite isn't configured to allow this key to clone the gitolite repo.

**Comment by majaesch** [comment]
Hmm wait a minute, i'm really confused now!

Which keys are needed in /opt/redmine/apps/redmine/.ssh/

the from the redmine user (which was used for gl-setup ~/redmine.pub)
or the the from ~git/.ssh?

As I mentioned earlier cloning as redmine user works (but prompt for the rsa passphrase)
redmine user was added with --disabled-password [1]

[1] http://xdissent.com/2010/05/04/github-clone-with-redmine/#create-a-redmine-user

**Comment by ericpaulbishop** [comment]
You need to put a key which has read/write access to the gitolite admin repo in /opt/redmine/apps/redmine/.ssh/

**Comment by gigaroby** [comment]
I tried again, starting everything from scratch. I installed chiliproject and tested if it was working.
Then I generated the rsa keys for the user chiliproject (i run chiliproject as that user with spawn-fcgi) and I installed gitolite on user git using the public key of the chiliproject user.
And still it doesn't work.
I really don't know what the problem is but is driving me insane xD

Edit: Good news (I hope) is that this time in the /tmp/redmine_git_hosting directory there are more files and folders.
ls -lH /tmp/redmine_git_hosting :

drwx------ 2 chili chili 4096 Sep 26 22:49 gitolite-admin
-r-xr-x--- 1 chili chili  112 Sep 26 22:49 gitolite_admin_ssh
-rw-r--r-- 1 chili chili    0 Sep 26 22:49 redmine_git_hosting_lock
-r-xr-x--- 1 chili chili  236 Sep 26 22:49 run_as_git_user
-r-xr-x--- 1 chili chili  167 Sep 26 22:49 run_git_as_git_user

ls -lH /tmp/redmine_git_hosting/gitolite-admin :
total 0

The error is still the same btw (in production.log) :

Processing ProjectsController#create (for 87.8.16.154 at 2011-09-26 22:49:37) [POST]
  Parameters: {"commit"=>"Save", "action"=>"create", "authenticity_token"=>"Q/GVdociaXu82k4acYVe4WkVCHoqjP2SE4bJdv9d7Qc=", "project"=>{"name"=>"test", "tracker_ids"=>["1", "2", "3", ""], "homepage"=>"", "is_public"=>"1", "description"=>"", "identifier"=>"test", "enabled_module_names"=>["repository", ""]}, "controller"=>"projects"}
Redirected to http://pm.glados-rebooted.eu/projects/test/settings
Cloning gitolite-admin repository
Our hook is already installed

Errno::ENOENT (No such file or directory - /tmp/redmine_git_hosting/gitolite-admin/conf/gitolite.conf):
  vendor/plugins/redmine_git_hosting/app/models/git_hosting_observer.rb:19:in `set_update_active'
  public/dispatch.fcgi:24

Rendering /srv/http/apps/chiliproject/public/500.html (500 Internal Server Error)

**Comment by ericpaulbishop** [comment]
Gigaroby... I think you just described your problem.  You don't want to use the public key of the chiliproject user, but rather the key stored in the .ssh directory under the chiliproject rails root.

**Comment by gigaroby** [comment]
the chiliproject rails root and the chiliproject user home directory are actually the same directory: /srv/http/apps/chiliproject/.
Therefore my ssh keys are correct, I belive. (of course I changed the plugin init.rb to match id_rsa and id_rsa.pub instead of the default values and then I double checked in the administration panel).

**Comment by ericpaulbishop** [comment]
What happens if you do what I had majaesch above do:

```
sudo su [your_chiliproject_user]
env GIT_SSH="/tmp/redmine_git_hosting/gitolite_admin_ssh" git clone git@server:gitolite-admin.git
```

Do you get errors?

**Comment by gigaroby** [comment]
It works.

Cloning into gitolite-admin...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (10/10), done.

**Comment by ericpaulbishop** [comment]
Okay, then your issue is completely different than that of majaesch.  

It looks like you actually have a gitolite-admin directory now.  What is in it? Just do an ls

**Comment by gigaroby** [comment]
It is in my previous post, the directory is empty.

ls -lH /tmp/redmine_git_hosting/gitolite-admin :
total 0

**Comment by ericpaulbishop** [comment]
Try this: Edit the git_hosting.rb file in [chiliproject_root]/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb, at line 273
Before editing it should look like:

```
%x[env GIT_SSH=#{gitolite_ssh()} git clone #{git_user}@#{Setting.plugin_redmine_git_hosting['gitServer']}:gitolite-admin.git #{local_dir}/gitolite-admin]
```

Update so that it dumps both stdout and stderr from this command to a file in /tmp, so it now reads

```
%x[env GIT_SSH=#{gitolite_ssh()} git clone #{git_user}@#{Setting.plugin_redmine_git_hosting['gitServer']}:gitolite-admin.git #{local_dir}/gitolite-admin >/tmp/CLONE_TEST.txt 2>&1]
```

Then remove what is currently in /tmp/redmine_git_hosting and restart the web server.  Wait until it fails again and post the contents of /tmp/CLONE_TEST.txt here

**Comment by gigaroby** [comment]
[root@GLaDOS ~]# cat /tmp/CLONE_TEST.txt 
fatal: Could not change back to '/home/roberto': Permission denied

roberto is my normal user and I don't see what it has to do with all this, the only thing I do with it is to invoke spawn-fcgi trough sudo.

**Comment by gigaroby** [comment]
I might have figured out the problem.
I guess when I run the dispatch.fcgi with spawn-fcgi somewhere there is an environment variable that is still set to "/home/<userwholaunchedscript>" and so git has trouble trying to cd to there.
But I don't understand why since I can tell spawn-fcgi which user I want to run as and I always put chili.

**Comment by majaesch** [comment]
Maybe its another source but it's still not working for me.

I start - once again - from the beginning! I have no clue whats wrong! I only follow [tutorials](http://www.davedevelopment.co.uk/2010/12/05/how-to-install-gitolite-on-ubuntu-10-10-maverick-meerkat/)!
It would be kind of you if you could check my gitolite settings.

```
redmine@mft:~$ git clone git@mft:gitolite-admin
Initialized empty Git repository in /opt/redmine/gitolite-admin/.git/
Enter passphrase for key '/opt/redmine/.ssh/id_dsa':
remote: Counting objects: 26, done.
remote: Compressing objects: 100% (21/21), done.
Receiving objects: 100% (26/26), 3.30 KiB, done.
Resolving deltas: 100% (2/2), done.
remote: Total 26 (delta 2), reused 0 (delta 0)

redmine@mft:~/gitolite-admin$ cat gitolite-admin/conf/gitolite.conf
repo    gitolite-admin
        RW+     =   redmine majaesch git

redmine@mft:~/gitolite-admin$ ls -lah gitolite-admin/keydir/*.pub
-rw-r--r-- 1 redmine redmine 597 2011-09-27 16:05 gitolite-admin/keydir/git.pub
-rw-r--r-- 1 redmine redmine 394 2011-09-27 16:05 gitolite-admin/keydir/majaesch.pub
-rw-r--r-- 1 redmine redmine 601 2011-09-27 16:05 gitolite-admin/keydir/redmine.pub
```

redmine home is `/opt/redmine` and was created with `$ adduser ... --disabled-password ...`!
all `*.pub` are from `~/.ssh/id_dsa`. created with `ssh-keygen -t dsa` (Except of majaesch, here I used a rsa key)

You say earlier that I shouldn't be prompted for a passphrase! 
Is this so far a valid base for the plugin?

PS: majaesch has a password and will promoted or the my id_rsa passphrase.

**Comment by ericpaulbishop** [comment]
Alright... I'm going to be blunt.  The purpose of the issues tracker is to report bugs.  I am convinced that this isn't a bug, and that you have mis-configured the software.  I am very willing to try to fix bugs -- my motivation for responding and debugging problems is that I want to improve the software, NOT to provide free tech support.

Gigaroby had something odd with his rails setup (running through fcgi is highly unusual), and I am also convinced, given the output the first time around, that your(majaesch) public key is mis-configured somehow.  

If you dig a little deeper and can find a way for me to reliably reproduce this issue, and that it is caused by a software defect, I'll be more than happy to address it.  However, I'm not interested in walking you through yet another round of debugging (since you re-installed you should be running ALL the tests I listed above again to see if you get the same result) and figuring out where you've screwed up.

**Comment by majaesch** [comment]
Okay one more last words before you can just blame me by saying I screw up. (this text will NOT blame you! just my view of the story end)

I could fix the issue now on my own by using a key for the user redmine which has NO passphrase. According to you that is what YOU expect. As far I understand it's valid to use keys with passphrases for gitolite users. So I it's normal that I was prompted for the passphrase for such keys.

I think it's a non-documented detail of your plugin. I mean you should mention that in your tutorial explicitly, because it seems to be an important detail!

When this is no bug of the plugin okay, but it's at least an issue of your documentation. So I convinced it's belong in this tracker.

Once again, I don't blame you at all! I just trapped in an "issue" with your plugin (which I thank for). And with my report and solution I want to help you, so other users are happy with your plugin.

Have a nice day!

PS: If I'm wrong with the passphrases, please teach me! Otherwise I hope it was at least helpful.

**Comment by serbulent** [comment]
On ubuntu 12.04 I run redmine with apache. So I use user www-data to run redmine. I add www-data user to gitolite.conf for repos I use and add public key (*.pub file under redmine .ssh) to gitolite keydir with name www-data.pub . And it   works now.
