### ISSUE TITLE
Add ability to organize repositories?

### ISSUE THREAD

**Issue by rchady** [ericpaulbishop/redmine_git_hosting#98]
I was wondering if it would be possible to designate where all the chiliproject/redmine managed repositories are stored in the gitolite repository?  Right now all the repositories get created at the top level of the gitolite repository structure.  It would be very useful to be able to specify that all of the managed repositories get created under a sub-folder in gitolite.  

For example, instead of a project of Parent1 Project / Client1 Project being created in repositories/parent1/client1, providing a 'managedRepositoryBase' parameter of "projects/" would result in them being created in repositories/projects/parent1/client.  This would be even more helpful when you have repositories being managed in gitolite that are not in Redmine or ChiliProject.

**Comment by rchady** [comment]
This also is a feature request, not a bug.

**Comment by ericpaulbishop** [comment]
Generally, I just close all feature request issues unless there's a patch/code attached.  Patches are very welcome.  I mostly develop this project for myself, and while I'm more than happy to share with others I don't really feel inclined to implement every feature someone might want or find useful.  I generally implement features either when I want them or when someone wants to contribute.

Bugs on the other hand... might bite me when I'm not expecting them, so I go out of my way to address bug reports so that I don't end up stuck with the same issues when I least want them.
